[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-production.txt"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 10

[[services]]
name = "api"
source = "."
builder = "nixpacks"
buildCommand = "pip install -r requirements-production.txt"
startCommand = "uvicorn src.api.main_production:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "worker"
source = "."
builder = "nixpacks"
buildCommand = "pip install -r requirements-production.txt"
startCommand = "celery -A src.workers.celery_app worker --loglevel=info"

[[services]]
name = "beat"
source = "."
builder = "nixpacks"
buildCommand = "pip install -r requirements-production.txt"
startCommand = "celery -A src.workers.celery_app beat --loglevel=info"
